### PR TITLE
i hate newlines

### PR DESCRIPTION
**Pull request by Laboredih123**
bad newlines

## Changelog
🆑
del: Removed all the instances of the firelock window shutters from Corgstation
/🆑

### CODE REVIEW

**Comment by Laboredih123** [comment]
alright that idk how to fix

**Review by KubeRoot — CHANGES_REQUESTED** [review]
Please include a changelog, as well as mentions for where the changes came from.

**Comment by KubeRoot** [comment]
Also, do note map files we're not using should be *identical* to upstream files at the point in the repo history we're at in regards to mirrored PRs. This is because, even if a map is the same, if the map file differs in how things are ordered, for example, it can cause conflicts in every mirrored PR that require merge drivers to be applied manually every time.

I haven't checked if that's the case, but it's also hard to check given this PR applies changes without any information for where those changes came from.

**Comment by Laboredih123** [comment]
dont need changelog, this only touches the newline erroring the lint and copy pastes unused maps from upstream

**Comment by Laboredih123** [comment]
alright maybe changelog needed the actions are getting annoying

**Pull request closed without merging**
