### PR TITLE
Beemerge

### PR DESCRIPTION
**Pull request by MaltVinegar**
## About The Pull Request

Merges the last 500 or so PRs merge on Beestation
Still needs some of fixes and testing

## Changelog
:cl:
code: updates code to latest Bee
/:cl:

### CODE REVIEW

**Comment by itsmeow** [comment]
Terrifying PR

**Comment by JixS4v** [comment]
This PR is completely normal what do you mean :trollface:

**Comment by MaltVinegar** [comment]
Every single change which our PR mirror bot had previously made caused a merge conflict
I had to resolve about 500 of them :skull:

**Comment by KubeRoot** [comment]
> Terrifying PR

**Comment by KubeRoot** [comment]
Sorry, misclick

**Pull request merged**
